# Generated by Django 3.2.10 on 2021-12-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_celda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cilindros', models.IntegerField()),
                ('Tipo_cilindro', models.CharField(max_length=9)),
                ('Tipo_metal', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Historial_control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_D_celda', models.BooleanField()),
                ('A_D_colocacion', models.BooleanField()),
                ('A_D_taladrado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Mensajes_celda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notificaciones_clasificacion', models.CharField(max_length=70)),
                ('notificaciones_colocacion', models.CharField(max_length=70)),
            ],
        ),
    ]
